### ISSUE TITLE
Travis CI is crashing

### ISSUE THREAD

**Issue by honzajavorek** [pyvec/pyvo.cz#132]
See e.g. https://travis-ci.org/github/pyvec/pyvo.cz/builds/662386759:

```
$ python -m pytest -vv test_pyvocz

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 267, in load_setuptools_entrypoints

    plugin = ep.load()

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2410, in load

    self.require(*args, **kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in require

    items = working_set.resolve(reqs, env, installer, extras=self.extras)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve

    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.VersionConflict: (pytest 4.3.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pytest>=5.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/opt/python/3.6.7/lib/python3.6/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pytest.py", line 89, in <module>

    raise SystemExit(pytest.main())

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 60, in main

    config = _prepareconfig(args, plugins)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 195, in _prepareconfig

    pluginmanager=pluginmanager, args=args

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/hooks.py", line 284, in __call__

    return self._hookexec(self, self.get_hookimpls(), kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec

    return self._inner_hookexec(hook, methods, kwargs)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>

    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall

    gen.send(outcome)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/helpconfig.py", line 93, in pytest_cmdline_parse

    config = outcome.get_result()

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result

    raise ex[1].with_traceback(ex[2])

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall

    res = hook_impl.function(*args)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 654, in pytest_cmdline_parse

    self.parse(args)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 871, in parse

    self._preparse(args, addopts=addopts)

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/_pytest/config/__init__.py", line 816, in _preparse

    self.pluginmanager.load_setuptools_entrypoints("pytest11")

  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pluggy/manager.py", line 273, in load_setuptools_entrypoints

    message="Plugin %r could not be loaded: %s!" % (ep.name, e),

pluggy.manager.PluginValidationError: Plugin 'flask' could not be loaded: (pytest 4.3.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('pytest>=5.2'))!
```

**Comment by messa** [comment]
Fixed by #131
